"""
Interleaved-block cross-validation (Pillow scheme) for a 50-mouse x 20-session
cohort, as a SLURM job array on the Allen Institute HPC.

MMLPF (+ perseveration) vs PsyTrack, both masked identically: held-out blocks of
20 consecutive trials inside each session, hyperparameters fit on the remaining
trials only, all data kept as regressors.

THREE STAGES
------------
    1. prepare  (login node, once)  -- query the database, cache per-subject
                                       trial arrays to .npz
    2. run      (job array, 50 tasks) -- one subject per task, reads only the
                                         cache, writes one CSV per subject
    3. combine  (login node)        -- merge CSVs, summarise, plot

Stage 1 exists because compute nodes frequently cannot reach the database, and
because 50 tasks hammering it simultaneously is antisocial even where they can.
Caching first also makes the array reproducible: every task reads identical
bytes, so a rerun cannot silently pick up a different session set.

    python hpc_block_cv.py prepare --cache-dir $CACHE
    sbatch hpc_block_cv_array.sh                     # generated by --write-sbatch
    python hpc_block_cv.py combine --out-dir $OUT

AGGREGATION
-----------
Unit of replication is the SUBJECT. Placements within a session differ only by
an arbitrary random mask, and sessions within a subject are repeated measures on
one animal, so treating either as independent inflates n by ~200x and produces a
p-value describing the block-placement RNG rather than the cohort.

    placement -> per-(subject, session) MEDIAN over placements
              -> per-subject MEDIAN over sessions
              -> across-subject paired test, n = subjects

Median rather than mean at both inner levels: on some animals the particle
filter destabilises on particular placements and scores worse than the base
rate, and one such placement moves a mean by more than the effect being
measured.
"""

import argparse
import glob
import os
import sys
import time
import traceback

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import block_cv as bc
import mmlpf_vs_psytrack_cv as cv

N_SUBJECTS = 50
N_SESSIONS = 20
MIN_TRIALS = 200          # valid trials needed for a session to be scored
BLOCK = 20                # held-out block length (Pillow: 10-20)
TEST_FRAC = 0.2
SEEDS = 10                # block placements per session

RESULT_COLUMNS = [
    "subject_id", "session_number", "seed", "n_trials", "n_test", "block",
    "base_bits", "glm_bits", "mmlpf_bits", "diff_bits",
    "glm_sigma", "sigma_alpha", "sigma_beta", "sigma_phi",
    "mean_beta", "max_beta", "mean_phi",
    "mmlpf_loss_conc", "mmlpf_worst_bits", "glm_loss_conc", "glm_worst_bits",
    "seconds", "error",
]


# ---------------------------------------------------------------------------
# stage 1: prepare the cache
# ---------------------------------------------------------------------------
def prepare(cache_dir, n_subjects=N_SUBJECTS, n_sessions=N_SESSIONS,
            min_trials=MIN_TRIALS):
    """Query the database once and cache per-subject arrays.

    Subject selection is alphabetical by subject_id among those that qualify --
    deliberately independent of how any subject scored under any previous
    analysis, so the cohort is not selected on the outcome.
    """
    import aind_dynamic_foraging_database as db

    os.makedirs(cache_dir, exist_ok=True)
    print(f"COHORT_QUERY: {cv.COHORT_QUERY}", flush=True)

    sessions = db.select_sessions(where=cv.COHORT_QUERY).sort_values(
        by=["subject_id", "session_date"])
    counts = sessions["subject_id"].value_counts()
    eligible = sorted(str(s) for s in counts[counts >= n_sessions].index)
    print(f"{len(counts)} subjects have >=1 qualifying session; "
          f"{len(eligible)} have >= {n_sessions}", flush=True)
    if len(eligible) < n_subjects:
        print(f"WARNING: only {len(eligible)} subjects meet the "
              f">= {n_sessions}-session requirement (asked for {n_subjects}). "
              f"Using all {len(eligible)}.", flush=True)
    picked_subjects = eligible[:n_subjects]

    manifest = []
    for i, sid in enumerate(picked_subjects, 1):
        subj = sessions[sessions["subject_id"].astype(str) == sid].head(n_sessions)
        trials = db.fetch_trials(subj, columns=["animal_response", "earned_reward"])
        groups = list(trials.groupby(["session_date", "session_id"], sort=True))
        keep = []
        for j, (key, g) in enumerate(groups, 1):
            v = g[g["animal_response"] != 2]
            if len(v) >= min_trials:
                keep.append(dict(
                    session_number=j,
                    session_date=str(key[0]), session_id=str(key[1]),
                    choices=v["animal_response"].astype(int).values,
                    rewards=v["earned_reward"].astype(int).values,
                    n_raw=len(g), n_ignored=int((g["animal_response"] == 2).sum())))
        if not keep:
            print(f"  [{i}/{len(picked_subjects)}] {sid}: no session with "
                  f">= {min_trials} valid trials, skipping", flush=True)
            continue

        path = os.path.join(cache_dir, f"{sid}.npz")
        np.savez_compressed(
            path,
            session_numbers=np.array([k["session_number"] for k in keep]),
            session_dates=np.array([k["session_date"] for k in keep]),
            session_ids=np.array([k["session_id"] for k in keep]),
            n_raw=np.array([k["n_raw"] for k in keep]),
            n_ignored=np.array([k["n_ignored"] for k in keep]),
            # ragged: store concatenated + offsets
            choices=np.concatenate([k["choices"] for k in keep]),
            rewards=np.concatenate([k["rewards"] for k in keep]),
            offsets=np.cumsum([0] + [len(k["choices"]) for k in keep]))
        manifest.append(dict(subject_id=sid, n_sessions=len(keep),
                             total_valid=int(sum(len(k["choices"]) for k in keep)),
                             path=path))
        print(f"  [{i}/{len(picked_subjects)}] {sid}: {len(keep)} sessions, "
              f"{sum(len(k['choices']) for k in keep)} valid trials", flush=True)

    mf = pd.DataFrame(manifest)
    mf_path = os.path.join(cache_dir, "manifest.csv")
    mf.to_csv(mf_path, index=False)
    print(f"\nwrote {mf_path}: {len(mf)} subjects, "
          f"{int(mf['n_sessions'].sum())} sessions, "
          f"{int(mf['total_valid'].sum())} valid trials", flush=True)
    print(f"array range for sbatch: --array=0-{len(mf)-1}%50", flush=True)
    return mf


def load_cached_subject(cache_dir, subject_id):
    """Return [(session_number, choices, rewards, n_raw, n_ignored), ...]."""
    z = np.load(os.path.join(cache_dir, f"{subject_id}.npz"), allow_pickle=False)
    off = z["offsets"]
    out = []
    for i in range(len(off) - 1):
        out.append((int(z["session_numbers"][i]),
                    z["choices"][off[i]:off[i+1]],
                    z["rewards"][off[i]:off[i+1]],
                    int(z["n_raw"][i]), int(z["n_ignored"][i])))
    return out


# ---------------------------------------------------------------------------
# stage 2: one array task = one subject
# ---------------------------------------------------------------------------
def _placement(args):
    """Module-level so multiprocessing can pickle it."""
    for var in ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS",
                "NUMEXPR_NUM_THREADS", "VECLIB_MAXIMUM_THREADS"):
        os.environ[var] = "1"
    sid, sess_no, choices, rewards, seed, block, test_frac = args
    row = {c: np.nan for c in RESULT_COLUMNS}
    row.update(subject_id=sid, session_number=sess_no, seed=seed, error="")
    t0 = time.time()
    try:
        res, _ = bc.score_session(choices, rewards, block=block,
                                  test_frac=test_frac, seed=seed,
                                  smooth=False, workers=1, verbose=False)
        row.update({k: v for k, v in res.items() if k in RESULT_COLUMNS})
    except Exception as e:
        row["error"] = f"{type(e).__name__}: {e}"
        traceback.print_exc()
    row["seconds"] = round(time.time() - t0, 1)
    return row


def run_task(cache_dir, out_dir, task_id, seeds=SEEDS, block=BLOCK,
             test_frac=TEST_FRAC, cores=1):
    """Score every (session, placement) for the subject at manifest row task_id."""
    mf_path = os.path.join(cache_dir, "manifest.csv")
    if not os.path.exists(mf_path):
        raise FileNotFoundError(
            f"{mf_path} not found. Run the prepare stage once on the login node "
            f"before submitting the array:\n"
            f"    python hpc_block_cv.py prepare --cache-dir {cache_dir} "
            f"--subjects 50 --sessions 20\n"
            f"Compute nodes often cannot reach the database, which is why the "
            f"cache is built up front.")
    mf = pd.read_csv(mf_path)
    if task_id >= len(mf):
        print(f"task_id {task_id} >= {len(mf)} subjects in manifest -- "
              f"nothing to do (harmless if the array is wider than the cohort)")
        return None
    sid = str(mf.iloc[task_id]["subject_id"])
    os.makedirs(out_dir, exist_ok=True)
    out_csv = os.path.join(out_dir, f"{sid}.csv")

    done = set()
    if os.path.exists(out_csv):
        prev = pd.read_csv(out_csv)
        missing = [c for c in RESULT_COLUMNS if c not in prev.columns]
        if missing:
            stamp = time.strftime("%Y%m%d_%H%M%S")
            os.rename(out_csv, out_csv.replace(".csv", f"_old_{stamp}.csv"))
            print(f"existing CSV has an older schema (missing {missing}); "
                  f"moved aside", flush=True)
        else:
            done = {(int(r.session_number), int(r.seed)) for r in prev.itertuples()}
            print(f"resuming: {len(done)} placements already done", flush=True)

    sessions = load_cached_subject(cache_dir, sid)
    jobs = [(sid, sno, c, r, s, block, test_frac)
            for (sno, c, r, _nraw, _nign) in sessions
            for s in range(seeds) if (sno, s) not in done]
    print(f"subject {sid}: {len(sessions)} sessions, {len(jobs)} placements "
          f"to fit on {cores} core(s)", flush=True)
    if not jobs:
        return pd.read_csv(out_csv)

    def append(row):
        pd.DataFrame([row], columns=RESULT_COLUMNS).to_csv(
            out_csv, mode="a", header=not os.path.exists(out_csv), index=False)

    t_start = time.time()
    if cores > 1:
        import multiprocessing as mp
        with mp.Pool(cores) as pool:
            for n, row in enumerate(pool.imap_unordered(_placement, jobs), 1):
                append(row)
                el = time.time() - t_start
                print(f"[{n}/{len(jobs)}] s{row['session_number']} "
                      f"seed {row['seed']}: "
                      f"{row['error'] or f'''diff {row['diff_bits']:+.4f}'''} "
                      f"({row['seconds']}s, eta "
                      f"{el/n*(len(jobs)-n)/60:.0f} min)", flush=True)
    else:
        for n, job in enumerate(jobs, 1):
            row = _placement(job)
            append(row)
            el = time.time() - t_start
            print(f"[{n}/{len(jobs)}] s{row['session_number']} "
                  f"seed {row['seed']}: "
                  f"{row['error'] or f'''diff {row['diff_bits']:+.4f}'''} "
                  f"({row['seconds']}s, eta "
                  f"{el/n*(len(jobs)-n)/60:.0f} min)", flush=True)

    print(f"subject {sid} done in {(time.time()-t_start)/60:.1f} min", flush=True)
    return pd.read_csv(out_csv)


# ---------------------------------------------------------------------------
# stage 3: combine
# ---------------------------------------------------------------------------
def combine(out_dir, fig="cohort_block_cv_hpc.png",
            merged="cohort_block_cv_hpc.csv"):
    from scipy import stats

    files = sorted(f for f in glob.glob(os.path.join(out_dir, "*.csv"))
                   if "_old_" not in os.path.basename(f))
    if not files:
        raise RuntimeError(f"no per-subject CSVs found in {out_dir}")
    df = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)
    df.to_csv(merged, index=False)
    print(f"merged {len(files)} subject files -> {merged} ({len(df)} rows)")

    ok = df[(df["error"].isna()) | (df["error"] == "")].copy()
    ok["subject_id"] = ok["subject_id"].astype(str)
    n_err = len(df) - len(ok)
    if not len(ok):
        raise RuntimeError("every placement failed -- inspect the error column")

    per_sess = (ok.groupby(["subject_id", "session_number"])
                .agg(diff=("diff_bits", "median"),
                     glm=("glm_bits", "median"),
                     mmlpf=("mmlpf_bits", "median"),
                     base=("base_bits", "median"))
                .reset_index())
    blown = (ok.assign(b=ok["mmlpf_bits"] > ok["base_bits"])
             .groupby(["subject_id", "session_number"])["b"].sum()
             .reindex(pd.MultiIndex.from_frame(
                 per_sess[["subject_id", "session_number"]])).values)
    per_sess["n_blown"] = blown

    per_subj = (per_sess.groupby("subject_id")
                .agg(diff=("diff", "median"), glm=("glm", "median"),
                     mmlpf=("mmlpf", "median"), base=("base", "median"),
                     n_sessions=("diff", "size"), blown=("n_blown", "sum"))
                .sort_values("diff", ascending=False))
    vr = (ok.groupby("subject_id")
          .apply(lambda s: (s["mmlpf_bits"].std() / s["glm_bits"].std()) ** 2
                 if s["glm_bits"].std() > 0 else np.nan,
                 include_groups=False))
    per_subj["var_ratio"] = vr.reindex(per_subj.index).values

    n = len(per_subj)
    dd = per_subj["diff"].values
    print(f"\n{'='*74}")
    print(f"COHORT BLOCK-CV  ({n} subjects, {len(ok)} placements, {n_err} failed)")
    print("="*74)
    print(per_subj.round(4).to_string())

    wins = int((dd > 0).sum())
    print(f"\n{'-'*74}")
    print(f"MMLPF better on {wins}/{n} subjects")
    print(f"median gap {np.median(dd):+.4f} bits/trial   mean {dd.mean():+.4f}  "
          f"sd {dd.std(ddof=1):.4f}")
    print(f"IQR [{np.percentile(dd,25):+.4f}, {np.percentile(dd,75):+.4f}]")
    if n >= 3:
        t = stats.ttest_1samp(dd, 0.0)
        w = stats.wilcoxon(dd)
        print(f"paired t across subjects  t = {t.statistic:.2f}, p = {t.pvalue:.4g}")
        print(f"Wilcoxon signed-rank      p = {w.pvalue:.4g}")
        print(f"\nNOTE at n={n} a small mean gap will yield a small p-value; "
              f"lead with the\neffect size and the win fraction, not the p-value.")
    mb, mg, mm = (per_subj["base"].median(), per_subj["glm"].median(),
                  per_subj["mmlpf"].median())
    print(f"\ncohort medians: base {mb:.3f}  PsyTrack {mg:.3f}  MMLPF {mm:.3f}")
    if mg < mb:
        frac = (mb - mm) / (mb - mg)
        if frac <= 1.0:
            print(f"MMLPF captures {frac:.1%} of the structure PsyTrack does")
        else:
            print(f"MMLPF explains MORE than PsyTrack ({frac:.1%}) -- "
                  f"report the gap directly, not as a fraction")
    gap = float(np.median(dd))
    print(f"per-trial likelihood ratio 2^|gap| = {2**abs(gap):.3f}  "
          f"({'MMLPF' if gap > 0 else 'PsyTrack'} assigns that factor more "
          f"probability to the observed choice)")

    hi_var = per_subj[per_subj["var_ratio"] > 4]
    bl = per_subj[per_subj["blown"] > 0]
    print(f"\n{'-'*74}")
    print("filter stability, two criteria:")
    print(f"  MMLPF variance > 4x the GLM's       : {len(hi_var)}/{n} subjects")
    print(f"  >= 1 placement worse than base rate : {len(bl)}/{n} subjects")
    if len(hi_var):
        print(hi_var[["diff", "var_ratio", "blown", "n_sessions"]].round(3).to_string())

    _plot(per_subj, fig)
    return per_subj


def _plot(per_subj, fname):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    C_GLM, C_MM, GREY = "#c8511b", "#17a398", "#8a8a8a"
    s = per_subj.sort_values("diff")
    n = len(s)
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5.2),
                                   gridspec_kw={"width_ratios": [1, 1.2]})

    y = np.arange(n)
    cols = [GREY if b > 0 else (C_MM if v > 0 else C_GLM)
            for v, b in zip(s["diff"], s["blown"])]
    ax1.barh(y, s["diff"].values, color=cols, height=0.8)
    ax1.axvline(0, color="k", lw=1.0)
    ax1.axvline(s["diff"].median(), color=C_MM, ls="--", lw=1.2)
    if n <= 60:
        ax1.set_yticks(y); ax1.set_yticklabels(s.index, fontsize=5.5)
        ax1.set_ylabel("Subject")
    else:
        ax1.set_ylabel(f"Subject (sorted, n={n})")
    ax1.set_xlabel("PsyTrack minus MMLPF (bits/trial)")
    ax1.set_title(f"MMLPF better on {int((s['diff']>0).sum())}/{n} subjects",
                  loc="left")
    ax1.text(0.98, 0.015, "right = MMLPF better", transform=ax1.transAxes,
             ha="right", va="bottom", fontsize=6.5, color=GREY)
    if (s["blown"] > 0).any():
        ax1.text(0.02, 0.985, "grey = filter destabilised\non >=1 placement",
                 transform=ax1.transAxes, va="top", fontsize=6.5, color=GREY)
    ax1.margins(y=0.01)

    x = np.arange(n)
    o = s.sort_values("glm")
    ax2.plot(x, o["base"].values, "o-", color=GREY, ms=2.5, lw=0.9,
             label="base rate")
    ax2.plot(x, o["glm"].values, "o-", color=C_GLM, ms=2.5, lw=1.2,
             label="PsyTrack")
    ax2.plot(x, o["mmlpf"].values, "o-", color=C_MM, ms=2.5, lw=1.2,
             label="MMLPF + persev.")
    ax2.set_xlabel(f"Subject (sorted by PsyTrack, n={n})")
    ax2.set_ylabel("Held-out NLL (bits/trial)")
    ax2.set_title("Both models against the base rate", loc="left")
    ax2.legend(frameon=False, fontsize=7)
    ax2.text(0.015, 0.03, "lower = better", transform=ax2.transAxes,
             fontsize=6.5, color=GREY)

    for ax, L in zip((ax1, ax2), "ab"):
        ax.text(-0.13, 1.02, L, transform=ax.transAxes, fontsize=12,
                fontweight="bold", va="bottom")
    fig.tight_layout(w_pad=2.4)
    fig.savefig(fname, dpi=300, bbox_inches="tight")
    print(f"\nsaved {fname}")


# ---------------------------------------------------------------------------
# sbatch generator
# ---------------------------------------------------------------------------
SBATCH_TEMPLATE = """#!/bin/bash
#SBATCH -p celltypes
#SBATCH --job-name blockcv
#SBATCH --time {time}
#SBATCH --nodes 1
#SBATCH --mem {mem}
#SBATCH -c {cores}
#SBATCH --array=0-{last}%50
#SBATCH -o {log_dir}/blockcv_%A_%a.out
#SBATCH -e {log_dir}/blockcv_%A_%a.err

# One array task per subject. The %50 throttle matches the documented cap of
# ~50 simultaneously scheduled jobs; the rest queue and start as slots free.

set -euo pipefail

# pip/joblib scratch must live somewhere writable on /allen, not the default
export TMPDIR="{tmp_dir}"
mkdir -p "$TMPDIR" "{log_dir}" "{out_dir}"

# the parallelism is across subjects and placements, so keep BLAS single-threaded
# inside each worker -- oversubscribing the cores runs SLOWER than serial
export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export MKL_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export VECLIB_MAXIMUM_THREADS=1

source activate {env}
cd {code_dir}

python hpc_block_cv.py run \\
    --cache-dir {cache_dir} \\
    --out-dir {out_dir} \\
    --task-id "$SLURM_ARRAY_TASK_ID" \\
    --cores {cores} \\
    --seeds {seeds} \\
    --block {block} \\
    --test-frac {test_frac}
"""


def write_sbatch(path, n_tasks, code_dir, cache_dir, out_dir, log_dir, tmp_dir,
                 env, cores, mem, time_limit, seeds, block, test_frac):
    # every path in the script must be ABSOLUTE: the task does `cd $code_dir`
    # first, so a relative cache/out path would resolve somewhere else.
    # os.path.abspath alone is not enough -- on some sandboxed filesystems it
    # returns the input unchanged -- so join against cwd explicitly.
    def _abs(p):
        p = os.path.expanduser(str(p))
        if not p.startswith("/"):
            p = os.path.normpath(os.path.join(os.getcwd(), p))
        return p

    paths = {k: _abs(v) for k, v in
             dict(log_dir=log_dir, tmp_dir=tmp_dir, code_dir=code_dir,
                  cache_dir=cache_dir, out_dir=out_dir).items()}
    rel = [f"{k}={v}" for k, v in paths.items() if not v.startswith("/")]
    if rel:
        raise ValueError(
            "could not resolve these to absolute paths, and the array task "
            f"cd's before using them: {rel}. Pass absolute /allen/... paths.")
    txt = SBATCH_TEMPLATE.format(
        last=max(n_tasks - 1, 0), env=env, cores=cores, mem=mem,
        time=time_limit, seeds=seeds, block=block, test_frac=test_frac,
        **paths)
    with open(path, "w") as f:
        f.write(txt)
    os.chmod(path, 0o755)
    print(f"wrote {path}  ({n_tasks} array tasks)")
    print(f"  submit with: sbatch {path}")
    return path


# ---------------------------------------------------------------------------
def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("stage", choices=["prepare", "run", "combine", "write-sbatch"])
    ap.add_argument("--cache-dir", default="./cache")
    ap.add_argument("--out-dir", default="./results")
    # --array_id is the name used in the lab's existing submit scripts; keep it
    # as an alias so a subjob.sh written for either convention works
    ap.add_argument("--task-id", "--array_id", type=int, default=None,
                    dest="task_id")
    ap.add_argument("--subjects", type=int, default=N_SUBJECTS)
    ap.add_argument("--sessions", type=int, default=N_SESSIONS)
    ap.add_argument("--seeds", type=int, default=SEEDS)
    ap.add_argument("--block", type=int, default=BLOCK)
    ap.add_argument("--test-frac", type=float, default=TEST_FRAC)
    ap.add_argument("--min-trials", type=int, default=MIN_TRIALS)
    ap.add_argument("--cores", type=int, default=1)
    # write-sbatch options
    ap.add_argument("--sbatch-path", default="hpc_block_cv_array.sh")
    ap.add_argument("--code-dir", default=None)
    ap.add_argument("--log-dir", default=None)
    ap.add_argument("--tmp-dir", default=None)
    ap.add_argument("--env", default="foraging")
    ap.add_argument("--mem", default="8G")
    ap.add_argument("--time-limit", default="08:00:00")
    args = ap.parse_args()

    if args.stage == "prepare":
        prepare(args.cache_dir, n_subjects=args.subjects,
                n_sessions=args.sessions, min_trials=args.min_trials)

    elif args.stage == "run":
        if args.task_id is None:
            ap.error("--task-id is required for stage 'run' "
                     "(SLURM provides $SLURM_ARRAY_TASK_ID)")
        run_task(args.cache_dir, args.out_dir, args.task_id, seeds=args.seeds,
                 block=args.block, test_frac=args.test_frac, cores=args.cores)

    elif args.stage == "combine":
        combine(args.out_dir)

    elif args.stage == "write-sbatch":
        mf_path = os.path.join(args.cache_dir, "manifest.csv")
        if not os.path.exists(mf_path):
            ap.error(f"{mf_path} not found -- run stage 'prepare' first, so the "
                     f"array width matches the actual number of subjects")
        n_tasks = len(pd.read_csv(mf_path))
        code_dir = args.code_dir or os.path.dirname(os.path.abspath(__file__))
        log_dir = args.log_dir or os.path.join(code_dir, "logs")
        tmp_dir = args.tmp_dir or os.path.join(code_dir, "tmp")
        # do NOT mkdir these -- the generator may run somewhere the target paths
        # do not exist (or are not writable). The array script creates TMPDIR
        # itself at runtime; SLURM needs the log dir to exist, so make it on the
        # cluster before submitting:
        #     mkdir -p <log_dir>
        write_sbatch(args.sbatch_path, n_tasks, code_dir,
                     os.path.abspath(args.cache_dir),
                     os.path.abspath(args.out_dir), log_dir, tmp_dir,
                     args.env, args.cores, args.mem, args.time_limit,
                     args.seeds, args.block, args.test_frac)


if __name__ == "__main__":
    main()
